import string

Introduce_Ans = ["I am InfoBee"]
GREETING_INPUTS = (
    "hello", "hi", "hiii", "hii", "hiiii", "hiiii", "greetings", "sup", "whats up", "hey", "salam", "salaam", "aoa",
    "assalamoalikum", "asslam o alikum", "asalam o alikum", "assalam o alikum", "janab", "aslamalikum", "salamalikum", "slam", "jnab",
    "suna",
    "sunao")

GREETING_RESPONSES = [
    "Hi! Are you suffering from any health issues?(سلام! کیا آپ کسی صحت کے مسائل کا شکار ہیں؟ براہ کرم جواب دیں)"]
Basic_Q= (
    "yes", "y", "g", "jee", "han g", "han jee", "jee han", "han", "han g", "g han", "gg",
    "jee jee","yea", "yeah", "yo", "yup", "ya", "i am sick", "i am feeling sick", "i feel sick", "im feeling sick", "im sick",
    "i dont feel good", "i dont feel so good", "i am not feeling good", "im not feeling good", "diagnose me again", "again",
    "i want another diagnosis" , "yes i am sick", "yes i am feeling sick", "yes i feel sick", "yes im feeling sick", "yes im sick",
    "yes i dont feel good", "yes i dont feel so good", "yes i am not feeling good", "yes im not feeling good",
    "main bemar hoon", "mein bemar hoon", "mai bemar hoon", "ma bemar hoon", "main bemar hu", "mein bemar hu", "mai bemar hu",
    "ma bemar hu", "main bemar h", "mein bemar h", "mai bemar h", "ma bemar h", "main bemar", "mein bemar", "mai bemar",
    "ma bemar",
    "han g main bemar hoon", "han g mein bemar hoon", "han g mai bemar hoon", "han g ma bemar hoon", "han g main bemar hu", "han g mein bemar hu", "han g mai bemar hu",
    "han g ma bemar hu", "han g main bemar h", "han g mein bemar h", "han g mai bemar h", "han g ma bemar h", "han g main bemar", "han g mein bemar", "han g mai bemar",
    "han g ma bemar", "han jee main bemar hoon", "han jee mein bemar hoon", "han jee mai bemar hoon", "han jee ma bemar hoon", "han jee main bemar hu", "han jee mein bemar hu",
    "han jee mai bemar hu", "han jee ma bemar hu", "han jee main bemar h", "han jee mein bemar h", "han jee mai bemar h", "han jee ma bemar h", "han jee main bemar", "han jee mein bemar",
    "han jee mai bemar", "han jee ma bemar",
    "g han main bemar hoon", "g han mein bemar hoon", "g han mai bemar hoon", "g han ma bemar hoon", "g han main bemar hu", "g han mein bemar hu", "g han mai bemar hu",
    "g han ma bemar hu", "g han main bemar h", "g han mein bemar h", "g han mai bemar h", "g han ma bemar h", "g han main bemar", "g han mein bemar", "g han mai bemar",
    "g han ma bemar",
    "jee han main bemar hoon", "jee han mein bemar hoon", "jee han mai bemar hoon", "jee han ma bemar hoon", "jee han main bemar hu", "jee han mein bemar hu", "jee han mai bemar hu",
    "jee han ma bemar hu", "jee han main bemar h", "jee han mein bemar h", "jee han mai bemar h", "jee han ma bemar h", "jee han main bemar", "jee han mein bemar", "jee han mai bemar",
    "jee han ma bemar",
    "han main bemar hoon", "han mein bemar hoon", "han mai bemar hoon", "han ma bemar hoon", "han main bemar hu", "han mein bemar hu", "han mai bemar hu",
    "han ma bemar hu", "han main bemar h", "han mein bemar h", "han mai bemar h", "han ma bemar h", "han main bemar", "han mein bemar", "han mai bemar",
    "han ma bemar",
    "main bemaar hoon", "mein bemaar hoon", "mai bemaar hoon", "ma bemaar hoon", "main bemaar hu", "mein bemaar hu", "mai bemaar hu",
    "ma bemaar hu", "main bemaar h", "mein bemaar h", "mai bemaar h", "ma bemaar h", "main bemaar", "mein bemaar", "mai bemaar",
    "ma bemaar",
    "han g main bemaar hoon", "han g mein bemaar hoon", "han g mai bemaar hoon", "han g ma bemaar hoon", "han g main bemaar hu", "han g mein bemaar hu", "han g mai bemaar hu",
    "han g ma bemaar hu", "han g main bemaar h", "han g mein bemaar h", "han g mai bemaar h", "han g ma bemaar h", "han g main bemaar", "han g mein bemaar", "han g mai bemaar",
    "han g ma bemaar", "han jee main bemaar hoon", "han jee mein bemaar hoon", "han jee mai bemaar hoon", "han jee ma bemaar hoon", "han jee main bemaar hu", "han jee mein bemaar hu",
    "han jee mai bemaar hu", "han jee ma bemaar hu", "han jee main bemaar h", "han jee mein bemaar h", "han jee mai bemaar h", "han jee ma bemaar h", "han jee main bemaar", "han jee mein bemaar",
    "han jee mai bemaar", "han jee ma bemaar",
    "g han main bemaar hoon", "g han mein bemaar hoon", "g han mai bemaar hoon", "g han ma bemaar hoon", "g han main bemaar hu", "g han mein bemaar hu", "g han mai bemaar hu",
    "g han ma bemaar hu", "g han main bemaar h", "g han mein bemaar h", "g han mai bemaar h", "g han ma bemaar h", "g han main bemaar", "g han mein bemaar", "g han mai bemaar",
    "g han ma bemaar",
    "jee han main bemaar hoon", "jee han mein bemaar hoon", "jee han mai bemaar hoon", "jee han ma bemaar hoon", "jee han main bemaar hu", "jee han mein bemaar hu", "jee han mai bemaar hu",
    "jee han ma bemaar hu", "jee han main bemaar h", "jee han mein bemaar h", "jee han mai bemaar h", "jee han ma bemaar h", "jee han main bemaar", "jee han mein bemaar", "jee han mai bemaar",
    "jee han ma bemaar",
    "han main bemaar hoon", "han mein bemaar hoon", "han mai bemaar hoon", "han ma bemaar hoon", "han main bemaar hu", "han mein bemaar hu", "han mai bemaar hu",
    "han ma bemaar hu", "han main bemaar h", "han mein bemaar h", "han mai bemaar h", "han ma bemaar h", "han main bemaar", "han mein bemaar", "han mai bemaar",
    "han ma bemaar",
    "meri tabiyat kharab hai", "mere tabiyat kharab hai", "mery tabiyat kharab hai",
    "meri tabyt kharab hai", "mere tabyt kharab hai", "mery tabyt kharab hai",
    "meri tabyat kharab hai", "mere tabyat kharab hai", "mery tabyat kharab hai",
    "meri tabiyt kharab hai", "mere tabiyt kharab hai", "mery tabiyt kharab hai",
    "meri tabiyat khrb hai", "mere tabiyat khrb hai", "mery tabiyat khrb hai",
    "meri tabyt khrb hai", "mere tabyt khrb hai", "mery tabyt khrb hai",
    "meri tabyat khrb hai", "mere tabyat khrb hai", "mery tabyat khrb hai",
    "meri tabiyt khrb hai", "mere tabiyt khrb hai", "mery tabiyt khrb hai",
    "meri tabiyat kharb hai", "mere tabiyat kharb hai", "mery tabiyat kharb hai",
    "meri tabyt kharb hai", "mere tabyt kharb hai", "mery tabyt kharb hai",
    "meri tabyat kharb hai", "mere tabyat kharb hai", "mery tabyat kharb hai",
    "meri tabiyt kharb hai", "mere tabiyt kharb hai", "mery tabiyt kharb hai",
    "meri tabiyat khrab hai", "mere tabiyat khrab hai", "mery tabiyat khrab hai",
    "meri tabyt khrab hai", "mere tabyt khrab hai", "mery tabyt khrab hai",
    "meri tabyat khrab hai", "mere tabyat khrab hai", "mery tabyat khrab hai",
    "meri tabiyt khrab hai", "mere tabiyt khrab hai", "mery tabiyt khrab hai",
    "meri tabiyat kharab ha", "mere tabiyat kharab ha", "mery tabiyat kharab ha",
    "meri tabyt kharab ha", "mere tabyt kharab ha", "mery tabyt kharab ha",
    "meri tabyat kharab ha", "mere tabyat kharab ha", "mery tabyat kharab ha",
    "meri tabiyt kharab ha", "mere tabiyt kharab ha", "mery tabiyt kharab ha",
    "meri tabiyat khrb ha", "mere tabiyat khrb ha", "mery tabiyat khrb ha",
    "meri tabyt khrb ha", "mere tabyt khrb ha", "mery tabyt khrb ha",
    "meri tabyat khrb ha", "mere tabyat khrb ha", "mery tabyat khrb ha",
    "meri tabiyt khrb ha", "mere tabiyt khrb ha", "mery tabiyt khrb ha",
    "meri tabiyat kharb ha", "mere tabiyat kharb ha", "mery tabiyat kharb ha",
    "meri tabyt kharb ha", "mere tabyt kharb ha", "mery tabyt kharb ha",
    "meri tabyat kharb ha", "mere tabyat kharb ha", "mery tabyat kharb ha",
    "meri tabiyt kharb ha", "mere tabiyt kharb ha", "mery tabiyt kharb ha",
    "meri tabiyat khrab ha", "mere tabiyat khrab ha", "mery tabiyat khrab ha",
    "meri tabyt khrab ha", "mere tabyt khrab ha", "mery tabyt khrab ha",
    "meri tabyat khrab ha", "mere tabyat khrab ha", "mery tabyat khrab ha",
    "meri tabiyt khrab ha", "mere tabiyt khrab ha", "mery tabiyt khrab ha",
    "meri tabiyat kharab h", "mere tabiyat kharab h", "mery tabiyat kharab h",
    "meri tabyt kharab h", "mere tabyt kharab h", "mery tabyt kharab h",
    "meri tabyat kharab h", "mere tabyat kharab h", "mery tabyat kharab h",
    "meri tabiyt kharab h", "mere tabiyt kharab h", "mery tabiyt kharab h",
    "meri tabiyat khrb h", "mere tabiyat khrb h", "mery tabiyat khrb h",
    "meri tabyt khrb h", "mere tabyt khrb h", "mery tabyt khrb h",
    "meri tabyat khrb h", "mere tabyat khrb h", "mery tabyat khrb h",
    "meri tabiyt khrb h", "mere tabiyt khrb h", "mery tabiyt khrb h",
    "meri tabiyat kharb h", "mere tabiyat kharb h", "mery tabiyat kharb h",
    "meri tabyt kharb h", "mere tabyt kharb h", "mery tabyt kharb h",
    "meri tabyat kharb h", "mere tabyat kharb h", "mery tabyat kharb h",
    "meri tabiyt kharb h", "mere tabiyt kharb h", "mery tabiyt kharb h",
    "meri tabiyat khrab h", "mere tabiyat khrab h", "mery tabiyat khrab h",
    "meri tabyt khrab h", "mere tabyt khrab h", "mery tabyt khrab h",
    "meri tabyat khrab h", "mere tabyat khrab h", "mery tabyat khrab h",
    "meri tabiyt khrab h", "mere tabiyt khrab h", "mery tabiyt khrab h",)
Basic_Ans = "Okay! Tell me about your symptoms(مجھے اپنی علامات کے بارے میں بتائیں)"
Basic_Om = (
    "no", "n", "ni", "nahi", "nai", "nae", "nai g", "ni g", "ni jee", "koi nahi", "koi ni", "ni to", "nahi to", "naa",
    "nah", "na", "nah g", "i am fine", "no i am fine", "noi am fine", "nope", "na g" , "nahi g", "na jee", "nahi jee", "nai jee", "nah jee", "kuch nhi", "kuch nahi", )
Basic_AnsM = "Thank you! Visit again (شکریہ! دوبارہ تشریف لائیے گا)"
fev = ("i am suffering from fever", "i affected with fever", "i have fever", "i am experiencing fever", "im experiencing fever", "fever", "bukhar", "bukhaar", "mujhay bukhar ha", "mujhay bukhar hai",
       "mujhay bukhar h", "mujay bukhar h", "bukhar hai", "bukhar ha", "temperature", "body temperature", "temp", "mujay bukhar ha", "mujay bukhar hai",
       "mujhay bukhar ha", "mujhay bukhar hai",
       "mujhay bukhar h", "mujay bukhar h", "bukhar hai", "bukhar ha","mujay bukhar ha", "bukhar h", "mujay bukhar hai"
       "mujhey bukhar ha", "mujhey bukhar hai",
       "mujhey bukhar h", "mujey bukhar h", "mujey bukhar ha", "mujey bukhar hai"
       "mujhay bukhaar ha", "mujhay bukhaar hai",
       "mujhay bukhaar h", "mujay bukhaar h", "bukhaar hai", "bukhaar ha","mujay bukhaar ha", "bukhaar h", "mujay bukhaar hai"
       "mujhey bukhaar ha", "mujhey bukhaar hai",
       "mujhey bukhaar h", "mujey bukhaar h", "mujey bukhaar ha", "mujey bukhaar hai",
       "am suffering from fever", "affected with fever", "have fever", "am experiencing fever", "im experiencing fever",
       "suffering from fever", "affected by fever", "experiencing fever")
feve_r = (
    "Which type of fever you have? Please mention your symptoms then I will try to predict your disease. (آپ کو کس قسم کا بخار ہے؟ براہ کرم اپنی علامات لکھیں پھر میں آپ کی بیماری کا اندازہ لگانے کی کوشش کروں گا۔)")